# Generated by Django 5.2.6 on 2026-08-22 15:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Град')),
                ('capacity', models.PositiveIntegerField(help_text='Общ брой места, които залата побира.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимален капацитет')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['city', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='unique_venue_name_per_city')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Адресен идентификатор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Край')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Ако не се попълни, регистрациите се приемат до началото на събитието.', null=True, verbose_name='Краен срок за регистрация')),
                ('capacity', models.PositiveIntegerField(help_text='Общият брой места за това събитие. Не може да бъде надхвърлен.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Брой места')),
                ('status', models.CharField(choices=[('DRAFT', 'Чернова'), ('PUBLISHED', 'Публикувано'), ('CANCELLED', 'Отменено'), ('FINISHED', 'Приключило')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Променено на')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.venue', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Събитие',
                'verbose_name_plural': 'Събития',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('speaker', models.CharField(blank=True, max_length=150, verbose_name='Лектор / водещ')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Край')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Подредба')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='events.event', verbose_name='Събитие')),
            ],
            options={
                'verbose_name': 'Точка от програмата',
                'verbose_name_plural': 'Програма',
                'ordering': ['order', 'starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='program_item_ends_after_start')],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена (лв.)')),
                ('quota', models.PositiveIntegerField(help_text='Максимален брой билети от този тип.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Квота')),
                ('sales_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало на продажбите')),
                ('sales_end', models.DateTimeField(blank=True, null=True, verbose_name='Край на продажбите')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='Събитие')),
            ],
            options={
                'verbose_name': 'Билетен тип',
                'verbose_name_plural': 'Билетни типове',
                'ordering': ['price', 'name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'name'), name='unique_ticket_type_name_per_event'), models.CheckConstraint(condition=models.Q(('quota__gt', 0)), name='ticket_type_quota_positive'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ticket_type_price_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'starts_at'], name='events_even_organiz_e1d05f_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='event_capacity_positive'),
        ),
    ]
