# Generated by Django 5.2.6 on 2026-08-22 15:27

import django.db.models.deletion
import registration.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=registration.models.generate_registration_code, max_length=20, unique=True, verbose_name='Код на заявката')),
                ('status', models.CharField(choices=[('PENDING', 'Чака плащане'), ('PAID', 'Платена'), ('CANCELLED', 'Отказана')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Име за контакт')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Имейл за контакт')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Обща сума (лв.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Създадена на')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Платена на')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отказана на')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event', verbose_name='Събитие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума (лв.)')),
                ('method', models.CharField(choices=[('CARD', 'Банкова карта'), ('BANK', 'Банков превод'), ('CASH', 'В брой на място')], max_length=20, verbose_name='Начин на плащане')),
                ('transaction_ref', models.CharField(max_length=40, unique=True, verbose_name='Референтен номер')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Неуспешно')], default='SUCCESS', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на плащане')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='registration.registration', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Плащане',
                'verbose_name_plural': 'Плащания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникален идентификатор')),
                ('holder_name', models.CharField(max_length=200, verbose_name='Име на притежателя')),
                ('holder_email', models.EmailField(max_length=254, verbose_name='Имейл на притежателя')),
                ('price_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Платена цена (лв.)')),
                ('status', models.CharField(choices=[('RESERVED', 'Резервиран'), ('VALID', 'Валиден'), ('USED', 'Използван'), ('CANCELLED', 'Анулиран')], db_index=True, default='RESERVED', max_length=20, verbose_name='Статус')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/', verbose_name='QR код')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Издаден на')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event', verbose_name='Събитие')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='registration.registration', verbose_name='Заявка')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.tickettype', verbose_name='Билетен тип')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билети',
                'ordering': ['issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'status'], name='registratio_event_i_53f121_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', '-created_at'], name='registratio_user_id_cfc8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='registratio_event_i_84cacd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type', 'status'], name='registratio_ticket__1d9af8_idx'),
        ),
    ]
