# Generated by Django 5.2.6 on 2026-08-24 13:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума (€)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Обща сума (€)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Платена цена (€)'),
        ),
    ]
