# Generated by Django 5.2.6 on 2026-08-22 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Час на влизане')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Бележка')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='events.event', verbose_name='Събитие')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_checkins', to=settings.AUTH_USER_MODEL, verbose_name='Извършил проверката')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='registration.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Регистриран вход',
                'verbose_name_plural': 'Регистрирани входове',
                'ordering': ['-checked_in_at'],
                'indexes': [models.Index(fields=['event', '-checked_in_at'], name='checkin_che_event_i_1934fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('OK', 'Успешен вход'), ('DUPLICATE', 'Билетът вече е използван'), ('INVALID_SIGNATURE', 'Невалиден или подправен код'), ('NOT_FOUND', 'Билетът не е намерен'), ('WRONG_EVENT', 'Билет за друго събитие'), ('NOT_PAID', 'Билетът не е платен'), ('CANCELLED', 'Билетът е анулиран'), ('EVENT_NOT_ACTIVE', 'Събитието не е активно')], db_index=True, max_length=30, verbose_name='Резултат')),
                ('payload_preview', models.CharField(blank=True, max_length=60, verbose_name='Сканиран код (начало)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Час на сканиране')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='events.event', verbose_name='Събитие')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_logs', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='registration.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Запис от дневника',
                'verbose_name_plural': 'Дневник на сканиранията',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='checkin_sca_event_i_fd8a6e_idx')],
            },
        ),
    ]
