# Generated by Django 5.2.6 on 2026-08-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CONFIRMATION', 'Потвърждение за регистрация'), ('REMINDER', 'Напомняне за предстоящо събитие'), ('CANCELLATION', 'Потвърждение за отказ')], db_index=True, max_length=20, verbose_name='Вид')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Получател')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('status', models.CharField(choices=[('SENT', 'Изпратено'), ('FAILED', 'Неуспешно')], default='SENT', max_length=20, verbose_name='Статус')),
                ('error', models.TextField(blank=True, verbose_name='Съобщение за грешка')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Изпратено на')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='events.event', verbose_name='Събитие')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='registration.registration', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Изпратено писмо',
                'verbose_name_plural': 'Дневник на писмата',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['registration', 'kind'], name='notificatio_registr_90d2ba_idx'), models.Index(fields=['event', 'kind'], name='notificatio_event_i_7091db_idx')],
            },
        ),
    ]
